In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
# from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
# data  = load_iris()

X , y = load_iris(return_X_y = True)

In [ ]:
# split = StratifiedShuffleSplit(n_splits = 1 , test_size = 0.2)

# for test_idx , train_idx in split.split(X,y):
#     X_train , X_test = X[train_idx] , X[test_idx]
#     y_train , y_test = y[train_idx] , y[test_idx]




In [ ]:
# import matplotlib.pyplot as plt
# import numpy as np

# count = np.bincount(y_train)
# position = np.arange(3)

# print(count)

# plt.bar(position , count)
# plt.xticks(position , data.target_names)
# plt.tight_layout()


In [22]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 17 )

Standard Scaler

In [54]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled = scaler.transform(X_test) 

X_train_scaled = scaler.fit_transform(X_train)

This code does same thing as :

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

We fit and transform in training but only transform in testing becuase fit calculates mean and std deviation so it is like determining the answer first but when testing our model should work from what it has learned rather than what is the correct answer. This helps model to actually learn.

In [57]:
X_test_scaled

array([[-0.51974235,  1.8916694 , -1.32816828, -0.99726286],
       [ 0.1771189 , -0.36704033,  0.45510661,  0.44456296],
       [ 0.9901237 , -0.14116936,  0.845198  ,  1.49316355],
       [-0.17131172, -0.59291131,  0.23219725,  0.18241281],
       [ 0.40940599, -0.59291131,  0.62228864,  0.83778818],
       [ 0.29326244, -0.14116936,  0.67801598,  0.83778818],
       [-0.51974235, -0.14116936,  0.45510661,  0.44456296],
       [ 2.15155912,  1.66579843,  1.68110811,  1.36208848],
       [-0.40359881, -1.4963952 ,  0.06501523, -0.07973734],
       [-0.17131172, -1.27052423,  0.73374332,  1.09993833],
       [ 0.9901237 ,  0.53644356,  1.1238347 ,  1.7553137 ],
       [-1.10046006,  0.08470162, -1.2167136 , -1.39048808],
       [-0.17131172, -0.59291131,  0.45510661,  0.18241281],
       [-1.2166036 ,  0.76231454, -1.16098626, -1.259413  ],
       [ 0.75783661,  0.31057259,  0.78947066,  1.09993833],
       [-0.86817298,  1.66579843, -1.2167136 , -1.12833793],
       [-1.68117777, -0.

Manual approach for standard scaler

In [60]:
# import numpy as np


# X_train , X_test = np.array(X_train) , np.array(X_test)

# mean = np.mean(X_train , axis = 0)
# st_dev = np.std(X_train , axis = 0)


# mean_test = np.mean(X_train, axis = 0)
# st_dev_test = np.std(X_train, axis = 0)


# def custom_vectorized_func(x , mean , st_dev):
#     return (x - mean)/st_dev



# X_train_scaled = custom_vectorized_func(X_train , mean , st_dev)
# X_test_scaled =  custom_vectorized_func(X_test , mean_test, st_dev_test)




# OR



import numpy as np

X_train_scaled = (X_train - np.mean(X_train , axis =0)) / np.std(X_train , axis =0)

X_test_scaled = (X_test - np.mean(X_test , axis =0)) / np.std(X_test , axis =0)




Min Max Scaler

In [62]:
from sklearn.preprocessing import MinMaxScaler

In [72]:
scaler = MinMaxScaler()

In [73]:
X_train_scaled  = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_test_scaled
X_train_scaled

array([[5.4, 3.9, 1.3, 0.4],
       [6. , 2.9, 4.5, 1.5],
       [6.7, 3. , 5.2, 2.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [7.7, 3.8, 6.7, 2.2],
       [5.5, 2.4, 3.8, 1.1],
       [5.7, 2.5, 5. , 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.8, 4.5, 1.3],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.8, 1.5, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [5.2, 3.4, 1.4, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [5.6, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [5.5, 2.3, 4. , 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.8, 2.6, 4. , 1.2]])

Manual approach

In [ ]:
import numpy as np

X_min = np.min(X_train , axis = 0)
X_max = np.max(X_train , axis = 0)

X_train_scaled  = (X_train - X_min) / (X_max - X_min)
X_test_scaled = (X_test - X_min)/(X_max - X_min)


X_train_scaled
X_test_scaled

array([[0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.41666667, 0.29166667,